#!/bin/bash
#SBATCH --job-name=slurmquiz
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=1
#SBATCH --mem=1G
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=mrwood01@wm.edu               # change this!
#SBATCH -o /sciclone/home/mrwood01/logs/firstjob_%j.out # change this!
#SBATCH -e /sciclone/home/mrwood01/logs/firstjob_%j.err # change this!

#######job#########
echo "Hello World"
